spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_admin_tajwid?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: admin1234
minio:
  host: http://localhost
  port: 9000
  access-key: DVIOKS3IRD86I7V18WHK
  secret-key: Gf9Oeaq2BtOJ0DamzsbkmPL+e2DbJwyHzl7ZPQxa
  bucket:
    kuis: kuis