spring:
  datasource:
    url: jdbc:mysql://dbadmintajwid-service:3306/dbadmintajwid
    username: userX04
    password: FbaJis6NyUAVj44a
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true