spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_admin_tajwid?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: admin1234
minio:
  host: https://play.minio.io
  port: 9000
  access-key: Q3AM3UQ867SPQQA43P2F
  secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  bucket:
    kuis: kuis